name: 'prometheus-action-metrics'
description: 'A GitHub Action that sends metrics about GitHub Actions to Prometheus'
author: 'Noah Ispas'
inputs:
  prometheus_remote_write_url:
    required: true
    description: 'The URL of your Prometheus remote write endpoint'
  prometheus_username:
    required: true
    description: 'Prometheus username'
  prometheus_password:
    required: true
    description: 'Prometheus password (or API Key)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.prometheus_remote_write_url }}
    - ${{ inputs.prometheus_username }}
    - ${{ inputs.prometheus_password }}